{{- $fullName := include "wasp-ws-reading-service.fullname" . -}}
  {{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "wasp-ws-reading-service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          {{- range .Values.ingress.paths }}
          - pathType: Prefix
            path: {{ . }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
          {{- end }}
